"""followers

Revision ID: 39623f86d9e3
Revises: 650e86d457bc
Create Date: 2018-03-16 14:44:39.630170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39623f86d9e3'
down_revision = '650e86d457bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
